### ISSUE TITLE
Performance/RedundantBlockCall autocorrect breaks code

### ISSUE THREAD

**Issue by mhenrixon** [rubocop/rubocop-performance#338] opened 2023-01-31 10:37 UTC
Given the following method definition:

```ruby
  def self.lock!(**args, &block)
    lock = create(args: args)

    return false if lock.unlocked?
    return block.call(lock) if block

    lock
  rescue Exception => ex
    error = true
    raise ex
  ensure
    cleanup(lock, error) if block
  end
```

Running rubocop with autocorrect erroneously changes the code to the following:

```ruby
  def self.lock!(**args, &block)
    lock = create(args: args)

    return false if lock.unlocked?
    return yield(lock) if block

    lock
  rescue Exception => ex
    error = true
    raise ex
  ensure
    cleanup(lock, error) if block
  end
```

Now the block never gets called, and my tests are breaking. Clearly, the block parameter is needed as `block_given?` is supposed to be really slow?

This is the test that got broken:

```ruby
context "with a block" do
  before do
    allow(block).to receive(:call).and_call_original
  end
  
  it "yields" do
     expect { lock! }.to change { described_class.count }.by(1)
     expect(lock!).to eq("horrible")
     expect(block).to have_received(:call)
     last_lock = described_class.last!
     expect(last_lock.unlocked_at).to be_present
     expect(last_lock.unlock_reason).to eq("finished")
   end
 end
end
```

## RuboCop version

```
$ bundle exec rubocop -V
1.44.1 (using Parser 3.2.0.0, rubocop-ast 1.24.1, running on ruby 2.7.7) [x86_64-linux]
  - rubocop-performance 1.15.2
  - rubocop-rails 2.17.4
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.18.1
```

**Comment by fatkodima** [comment] 2023-01-31 14:42
Is this really a bug? Block is called, just not via the `.call` method. 

Testing if block was called should be done using something like this:
```ruby
called = false
block = -> { called = true }
# do something with block
assert called
```

**Comment by koic** [comment] 2023-02-02 04:06
@fatkodima Ah, sure. This doesn't seem to be a bug. 
@mhenrixon The diff below is the expected behavior.

```diff
@@ -2,7 +2,7 @@ def self.lock!(**args, &block)
   lock = create(args: args)

   return false if lock.unlocked?
-  return block.call(lock) if block
+  return yield(lock) if block

   lock
 rescue Exception => ex
```

Here is a minimal code example that expresses the same result.

```ruby
def foo(&block)
  block.call(42)
end
foo { |x| puts x } #=> 42

def bar(&block)
  yield(42)
end
bar { |x| puts x } #=> 42
```

If you're still having issues, can you provide a minimal repro?

**Comment by koic** [comment] 2023-02-06 03:16
I'm going to close this issue because it doesn't look like a bug. Please reopen with a minimal repro if you have any issues for that.

**Closed by koic** 2023-02-06 03:16 UTC
